export {
  applyFileTypeOperationEffect,
  applyFileTypeOperationServiceEffect,
  applyFileTypeOperationSync,
  BuiltInFileTypeDefinitions,
  BuiltInFileTypePlugins,
  BuiltInFileTypeRegistry,
  documentCodecFromFileTypePlugin,
  inspectFileEffect,
  inspectFileServiceEffect,
  inspectFileSync,
  JsonFileTypeDefinition,
  JsonFileTypePlugin,
  JsonPatchOperation,
  OperationDef,
  PdfAnnotation,
  PdfAnnotationDocument,
  PdfAnnotationPage,
  PdfContentEncoding,
  PdfFieldMetadata,
  makeSchemaIdeFileTypeRegistry,
  makeSchemaIdeFileTypeRegistryLayer,
  PdfFileTypeDefinition,
  PdfFileTypePlugin,
  PdfMetadata,
  PdfPageMetadata,
  PdfRect,
  PdfWidgetMetadata,
  RenderPageScreenshotOperation,
  SchemaIdeFileTypeError,
  UpdateFormAnnotationsOperation,
  YamlFileTypeDefinition,
  SchemaIdeFileTypeRegistry,
  YamlFileTypePlugin,
  type SchemaIdeFileTypeDefinition,
  type SchemaIdeFileTypeInspection,
  type SchemaIdeFileTypeInspectionExtra,
  type SchemaIdeFileTypeOperationDefinition,
  type SchemaIdeFileTypeOperationInfo,
  type SchemaIdeFileTypeOperationInput,
  type SchemaIdeFileTypeOperationResult,
  type SchemaIdeFileTypePlugin,
  type SchemaIdeFileTypeRegistryService,
} from "./file-type";
export { BuiltInFileTypeDefinitions as FileTypeDefinitions } from "./file-type-definitions";
export {
  JsonDocumentCodec,
  YamlDocumentCodec,
  BuiltInDocumentCodecs,
  codecForFormat,
  codecForPath,
  formatForPath,
  parseDocument,
  stringifyDocument,
  parseYaml,
  decodeYamlEither,
} from "./document-codec";
export { summarizeDiagnostics, parseErrorToDiagnostics } from "./diagnostics";
export {
  Workspace,
  isWorkspaceSchema,
  type WorkspaceDecodeOptions,
  type WorkspaceRouteId,
  type WorkspaceRouteMap,
  type WorkspaceRoutes,
  type WorkspaceRouteValue,
  type WorkspaceSchema,
  type WorkspaceValidationIssue,
  type FileEntry,
} from "./workspace-schema";
export {
  createReflection,
  sourceTreeFromFiles,
  validateSchemaIdeValue,
  validateSingleDocument,
  type SchemaIdeInputSchema,
} from "./validation";
export {
  buildReferenceIndex,
  getSchemaIdeCompletions,
  getSchemaIdeDefinitions,
  getSchemaIdeHover,
  getSchemaIdeQuickFixes,
  getSchemaIdeReferences,
  type SchemaIdeCompletionItem,
  type SchemaIdeCompletionResult,
  type SchemaIdeDefinition,
  type SchemaIdeHover,
  type SchemaIdeQuickFix,
  type SchemaIdeReference,
  type SchemaIdeWorkspaceTextEdit,
} from "./schema-language-service";
export {
  createEmptyFS,
  deleteFile,
  listFiles,
  normalizePath,
  readFile,
  sourceFilesToVirtualFs,
  virtualFsToSourceTree,
  writeFile,
  type VirtualFile,
  type VirtualFSState,
} from "./virtual-fs";
export { createMemorySourceRepository, type SourceRepository } from "./source-repository";
export {
  applyWorkspaceChange,
  canRedoWorkspaceChange,
  canUndoWorkspaceChange,
  checkoutWorkspaceRevision,
  createVersionedWorkspace,
  getCurrentWorkspaceRevision,
  getWorkspacePatchPaths,
  redoWorkspaceChange,
  undoWorkspaceChange,
  type VersionedWorkspaceState,
  type WorkspaceChange,
  type WorkspacePatch,
  type WorkspaceRevision,
  type WorkspaceRevisionActor,
  type WorkspaceRevisionMetadata,
} from "./workspace-history";
export type {
  AnySchema,
  ReflectedSchema,
  RouteMatch,
  SchemaIdeDiagnostic,
  SchemaIdeDiagnosticSource,
  SchemaIdeDocumentCodec,
  SchemaIdeDocumentFormat,
  SchemaIdeParseFailure,
  SchemaIdeParseResult,
  SchemaIdeParseSuccess,
  SchemaIdeReflection,
  SchemaIdeValidationSummary,
  SourceFile,
  SourceTree,
  ValidationResult,
} from "./types";
